version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn test -Dtest=AppTest
      - mvn package
      - tar -cvzf artifact.tar.gz appspec.yml target/main-app-0.1-SNAPSHOT.jar
artifacts:
  files:
    - artifact.tar.gz